# Sample data for the SQLite database
SAMPLE_DATA = [
    ("Alice", 30, "New York"),
    ("Bob", 25, "Los Angeles"),
    ("Charlie", 35, "Chicago"),
    ("Don", 30, "Charlotte"),
    ("Eve", 28, "Seattle"),
    ("Frank", 40, "Miami"),
    ("Grace", 22, "Boston"),
    ("Heidi", 29, "Denver"),
    ("Ivan", 31, "San Francisco"),
    ("Judy", 27, "Austin"),
    ("Karl", 33, "Houston"),
    ("Liam", 26, "Phoenix"),
    ("Mia", 24, "Philadelphia"),
    ("Nina", 32, "Dallas"),
    ("Oscar", 36, "Atlanta"),
    ("Paul", 38, "Seattle"),
    ("Quinn", 34, "San Diego"),
    ("Rita", 30, "Portland"),
    ("Sam", 29, "Las Vegas"),
    ("Tina", 28, "Orlando"),
    ("Uma", 31, "Baltimore"),
    ("Vera", 27, "Cleveland"),
    ("Will", 35, "Detroit"),
    ("Xena", 22, "Indianapolis"),
    ("Yara", 26, "Milwaukee"),
    ("Zane", 33, "Kansas City")
]